### ISSUE TITLE
解谜流程备份

### ISSUE THREAD

**Issue by bdcformpara** [Nikucyan/ARG#1]
不确定一些在ARG-List.md里的ARG需不需要备份，因为有部分已经有很完整的图文版walkthrough，还是只需要贴出相关链接即可？

**Comment by Nikucyan** [comment]
如果有很详细的帖子就可以不用吧，一些没有很详细的才需要手动重新整理，主要也是方便查找为目的
另外有一些相对有争议的建议本地备份一下
